### ISSUE TITLE
有没有可能可以魔改一下开源的Motrix,然后利用URL Scheme的方式实现自动下载

### ISSUE THREAD

**Issue by chuilishi** [f4team-cn/f4pan-web#17]
当前的下载步骤很繁琐,可以就单个下载按钮 ,如果motrix 没有响应就提示用户下载motrix,如果有的话就利用motrix://params 这种形式来自动创建任务

**Comment by Yingyya** [comment]
这个 Issues 已完成，https://github.com/f4team-cn/f4pan-web/commit/64749950d15931fe4fd54f45bb30db5fd58756e1
