### ISSUE TITLE
致前端开发人员

### ISSUE THREAD

**Issue by ZZ0YY** [f4team-cn/f4pan-web#2]
可能添加支持选中单级文件夹批量解析会更好且较容易实现？（）毕竟实现保留文件结构挺麻烦的，但是文件夹内文件批量解析需求量又大

**Comment by Yingyya** [comment]
已更新，https://github.com/f4team-cn/f4pan-web/commit/c0cf656d625a85fb78e4411183caf7adff4bcb62 。
