### ISSUE TITLE
RPC不能推送的可能原因

### ISSUE THREAD

**Issue by Cillo-x** [f4team-cn/f4pan-web#3]
今天发现推送到 Motrix 有时可以有时不行，在浏览器控制台发现许多报错Uncaught SyntaxError: invalid range in character class
![图片](https://github.com/user-attachments/assets/02310060-8cfa-4265-8d5d-ddfbd6334bca)
定位到下面这行代码
![图片](https://github.com/user-attachments/assets/9afe45ca-4504-4d99-9cc7-3dea9176336e)
源代码中在src/pages/Prased.vue:210
![图片](https://github.com/user-attachments/assets/10735067-2f91-4c84-b0fa-1fcc8cdce8dd)

这行代码好像是要把文件名之后的路径都删掉
报错原因是正则字符范围超出，原因是直接把${rndDir.value} 这个文件名变量拼接到正则表达式里去了，如果文件名有正则表达式的特殊字符，比如说 [ 和 ] 就会出错
![图片](https://github.com/user-attachments/assets/0c10f58e-4a69-4551-ba80-64480d8f1163)

可能的解决方法，把文件名中的特殊字符进行转义，比如这样
new RegExp(`/${B.value.replace(/[\[\]]/g, '\\$&')}.*`)

希望开发团队关注

**Comment by Yingyya** [comment]
是这个问题，非常感谢你的代码，我已经对这个问题进行修复。https://github.com/f4team-cn/f4pan-web/commit/e138d45962bed811244e1c634580de90eab3e2e3
