### ISSUE TITLE
部署好后为什么会出现加载完页面就变成空白页？

### ISSUE THREAD

**Issue by sadtear** [f4team-cn/f4pan-web#5]
https://txfd.zeroo.vip/#/

**Comment by Yingyya** [comment]
已找到可疑点，但暂时不能进行调试，稍后解决后会回复你。

**Comment by AGZZY11** [comment]
貌似是公告的问题

**Comment by Yingyya** [comment]
该问题已修复。https://github.com/f4team-cn/f4pan-web/commit/c327de0c72b2e1da3c382901ea7f9b90544ca8b5
