### ISSUE TITLE
建议把下载方式为web时的导出格式里的filename删去

### ISSUE THREAD

**Issue by sekurodesu** [f4team-cn/f4pan-web#7]
<img width="414" alt="无标题" src="https://github.com/user-attachments/assets/d40209bb-2309-4018-a40f-57ed575ab788">

如图，每次下载出来的压缩包里的结果文件里面都带着文件名，非常不方便复制直链下载。

建议直接把下载方式为web时的导出格式里的filename删去，或是提供两个选项选择，一个带filename，一个不带，然后默认选择不带filename的选项方便用户，谢谢。

**Comment by 1574242600** [comment]
请修改导出格式为 `{url}`

**Comment by sekurodesu** [comment]
这个修改可以永久保存设置吗？不然每次都要修改也有点麻烦，就是想做成能一直只有 {url} 这样的

**Comment by Yingyya** [comment]
修改后将会持久化保存，二次使用时不需要再次修改。如果需要不修改就能实现，请修改 `src/store/modules/user-store.ts` 后自建本程序。
